[formatting]
line_length = 79

[runtime]
auto_reload = "off"
watcher_on_save = "lazy"
output_max_bytes = 20000000
std_stream_max_bytes = 1000000
auto_instantiate = true
on_cell_change = "autorun"

[experimental]

[package_management]
manager = "uv"

[completion]
activate_on_typing = true
copilot = false

[snippets]
include_default_snippets = true
custom_paths = []

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[display]
code_editor_font_size = 14
cell_output = "above"
theme = "light"
dataframes = "rich"
default_width = "medium"

[server]
browser = "default"
follow_symlink = false

[ai]
rules = ""

[keymap]
preset = "default"
